### ISSUE TITLE
Client-Side Error

### ISSUE THREAD

**Issue by codistiano** [Manuel-heav/built#1]
After submitting a project filling all the wanted information, the homepage keeps showing the page 
"Application error: a client-side exception has occurred (see the browser console for more information)."

Looking through the console, found out a **TypeError** immediately after logging the session object:
- TypeError: Cannot read properties of null (reading 'default')

**Comment by Manuel-heav** [comment]
Hey there @codistiano, it's fixed now. Thanks!
